"""Bootstrap a wikip wiki directory.

Creates the standard layout under <wiki-dir>:
  pages/                   per-document pages will live here
  graph.json               empty knowledge graph
  _schema.json             default predicate vocabulary
  index.md                 stub TOC (regenerated by validate.py)

Idempotent: existing files are not overwritten. Re-run on an existing wiki
dir is a no-op (reports what already existed).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DEFAULT_PREDICATES = {
    "cites": "Page's document explicitly references the other paper, with no stronger relation.",
    "extends": "Page's document builds directly on the other paper's method, advancing or generalising it.",
    "compares-with": "Page's document benchmarks or compares its approach against the other paper.",
    "criticizes": "Page's document refutes, challenges, or substantively disagrees with the other paper.",
    "formalizes": "Page's document provides a formal definition for ideas the other paper introduces informally.",
    "applies": "Page's document applies methods from the other paper to a new problem or domain.",
    "surveys": "Page's document includes the other paper in a survey/review.",
    "motivates": "Page's document provides motivation/background that the other paper needs.",
    "disambiguates": "Page's document clarifies or distinguishes terms ambiguously used in the other paper.",
    "same-topic": "Page's document addresses the same topic without any direct relation above.",
}

INDEX_STUB = """# Wiki

This index is auto-generated by `wikip/scripts/validate.py`. Run validate to refresh.

No pages yet — add a document with the wikip skill to get started.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("wiki_dir", type=Path, help="path to wiki directory (created if missing)")
    args = ap.parse_args()

    wiki: Path = args.wiki_dir
    pages = wiki / "pages"
    graph = wiki / "graph.json"
    schema = wiki / "_schema.json"
    index = wiki / "index.md"

    created: list[str] = []
    skipped: list[str] = []

    pages.mkdir(parents=True, exist_ok=True)
    if not any(pages.iterdir()):
        # New empty pages dir — note we created it (or it was empty)
        created.append("pages/")
    else:
        skipped.append(f"pages/ ({sum(1 for _ in pages.iterdir())} entries already)")

    if not graph.exists():
        graph.write_text(json.dumps({"nodes": [], "edges": []}, indent=2) + "\n")
        created.append("graph.json")
    else:
        skipped.append("graph.json")

    if not schema.exists():
        schema.write_text(json.dumps({"predicates": DEFAULT_PREDICATES}, indent=2) + "\n")
        created.append("_schema.json")
    else:
        skipped.append("_schema.json")

    if not index.exists():
        index.write_text(INDEX_STUB)
        created.append("index.md")
    else:
        skipped.append("index.md")

    print(f"wiki dir: {wiki}")
    if created:
        print(f"  created: {', '.join(created)}")
    if skipped:
        print(f"  kept:    {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
