"""Bootstrap a wikip wiki directory.

Creates the standard layout under <wiki-dir>:
  pages/papers/            paper / video / pdf landing pages live here
  pages/concepts/          concept pages live here
  graph.json               empty knowledge graph
  _schema.json             default predicate vocabulary (typed by source/target)
  index.md                 stub TOC (regenerated by validate.py)

Idempotent: existing files are not overwritten. Re-run on an existing wiki
dir is a no-op (reports what already existed).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Predicates are typed by source-page type and target-page type. validate.py
# enforces these constraints. "*" means any page type.
DEFAULT_PREDICATES = {
    # Paper -> paper (literature relations)
    "cites": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper explicitly references the target paper, with no stronger relation.",
    },
    "extends": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper builds directly on the target paper's method, advancing or generalising it.",
    },
    "compares-with": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper benchmarks or compares its approach against the target paper.",
    },
    "criticizes": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper refutes, challenges, or substantively disagrees with the target paper.",
    },
    "applies": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper applies methods from the target paper to a new problem or domain.",
    },
    "surveys": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper includes the target paper in a survey/review.",
    },
    "motivates": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper provides motivation/background that the target paper needs.",
    },
    "disambiguates": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper clarifies or distinguishes terms ambiguously used in the target paper.",
    },
    "same-topic": {
        "from_type": "paper", "to_type": "paper",
        "description": "Source paper addresses the same topic as the target without any stronger relation.",
    },
    # Paper -> concept (where the concept lives in the literature)
    "defines": {
        "from_type": "paper", "to_type": "concept",
        "description": "Source paper provides a definition (formal or informal) for the concept.",
    },
    "discusses": {
        "from_type": "paper", "to_type": "concept",
        "description": "Source paper discusses, uses, or applies the concept without claiming to define it.",
    },
    "introduces": {
        "from_type": "paper", "to_type": "concept",
        "description": "Source paper is the historical origin or canonical introduction of the concept.",
    },
    # Concept -> concept (taxonomy / structure of ideas)
    "is-a": {
        "from_type": "concept", "to_type": "concept",
        "description": "Source concept is a kind of, or instance of, the target concept (subclass or specialisation).",
    },
    "part-of": {
        "from_type": "concept", "to_type": "concept",
        "description": "Source concept is a structural component of the target concept.",
    },
    "alternative-to": {
        "from_type": "concept", "to_type": "concept",
        "description": "Source concept is a competing or alternative formulation of the same idea as the target.",
    },
    "related-to": {
        "from_type": "concept", "to_type": "concept",
        "description": "Source concept is related to the target concept without any stronger relation.",
    },
}

INDEX_STUB = """# Wiki

This index is auto-generated by `wikip/scripts/validate.py`. Run validate to refresh.

No pages yet — add a document with the wikip skill to get started.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("wiki_dir", type=Path, help="path to wiki directory (created if missing)")
    args = ap.parse_args()

    wiki: Path = args.wiki_dir
    papers_dir = wiki / "pages" / "papers"
    concepts_dir = wiki / "pages" / "concepts"
    graph = wiki / "graph.json"
    schema = wiki / "_schema.json"
    index = wiki / "index.md"

    created: list[str] = []
    skipped: list[str] = []

    for d in (papers_dir, concepts_dir):
        existed = d.exists() and any(d.iterdir())
        d.mkdir(parents=True, exist_ok=True)
        rel = d.relative_to(wiki)
        if existed:
            skipped.append(f"{rel}/")
        else:
            created.append(f"{rel}/")

    if not graph.exists():
        graph.write_text(json.dumps({"nodes": [], "edges": []}, indent=2) + "\n")
        created.append("graph.json")
    else:
        skipped.append("graph.json")

    if not schema.exists():
        schema.write_text(json.dumps({"predicates": DEFAULT_PREDICATES}, indent=2) + "\n")
        created.append("_schema.json")
    else:
        skipped.append("_schema.json")

    if not index.exists():
        index.write_text(INDEX_STUB)
        created.append("index.md")
    else:
        skipped.append("index.md")

    print(f"wiki dir: {wiki}")
    if created:
        print(f"  created: {', '.join(created)}")
    if skipped:
        print(f"  kept:    {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
